-- MySQL Script generated by MySQL Workbench
-- Fri Jan 14 14:43:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema M7011e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema M7011e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `M7011e` DEFAULT CHARACTER SET utf8 ;
USE `M7011e` ;

-- -----------------------------------------------------
-- Table `M7011e`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M7011e`.`user` (
  `user_name` VARCHAR(60) NOT NULL,
  `password` VARCHAR(254) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  `prosumer` TINYINT NOT NULL,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_pic` VARCHAR(200) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M7011e`.`house_hold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M7011e`.`house_hold` (
  `closest_station_id` INT NOT NULL,
  `distans_to_station` FLOAT NOT NULL,
  `prosumer` TINYINT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`),
  CONSTRAINT `fk_house_hold_User`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `M7011e`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M7011e`.`power_plant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M7011e`.`power_plant` (
  `idpower_plant` INT NOT NULL,
  `buffert` FLOAT NOT NULL,
  `buffert_capacety` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`idpower_plant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M7011e`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M7011e`.`admin` (
  `admin_id` INT NOT NULL,
  `user_name` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `admin_pic` VARCHAR(190) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
